package yardımcı;

public class Değişkenler {

	public static final String UYGULAMA_ADI_VE_SURUMU = "Yeni Bir Programlama Dili Derleyicisi sürüm 0.0.2";

	public enum SÖZCÜK {
		TİP_00YOK,
		TİP_01İSİM,
		TİP_02OPERATÖR,
		TİP_03TAM_SAYI,
		TİP_04ONDALIKLI_SAYI,
		TİP_05METİN,
		TİP_06SATIR_SONU,
		TİP_07DEĞİŞKEN_TİPİ,
		TİP_08NOKTA,
		TİP_09ATAMA_SOLA,
		TİP_10ATAMA_SAĞA,
		TİP_11TANIMLAMA_SOLA,
		TİP_12TANIMLAMA_SAĞA,
		TİP_13ÖZELLİK,
		TİP_14AÇPARANTEZ,
		TİP_15KAPAPARANTEZ,
		TİP_16AÇSÜSLÜ,
		TİP_17KAPASÜSLÜ,
		TİP_18VİRGÜL
	}
	
	public enum CÜMLE {
		TİP_01DEĞİŞKENYENİ,
		TİP_02DEĞİŞKENSİL,
		TİP_03OPERATÖRİŞLEMİ,
		TİP_04FUNKSİYONÇAĞRISI,
		TİP_05SABİTATAMA,
		TİP_06DEĞİŞKENATAMA,
		TİP_07ASSEMBLY,
		TİP_08ASSEMBLYDATA,
		TİP_09ASSEMBLYRODATA
	}
	
	public enum FONKSİYON {
		TİP_01OPERATÖRFONKSİYON,
		TİP_02İSİMLİFONKSİYON,
		TİP_03ANAFONKSİYON
	}
	
	public enum SAKLAÇ {
		RAX, RBX, RCX, RDX, RBP, RSI, RDI, RSP, R8, R9, R10, R11, R12, R13, R14, R15
	}

}
